version: '3' 
 
# Define the services/containers to be run
services:
 client:
   build: ./client
   ports:
     - "80:4200"
 server: 
   build: ./server
   ports:
     - "8080:8080"
   environment:
     - MONGO_URL=mongodb://database:27017/mongodb
   links:
     - database
   depends_on:
     - database
 database:
   image: mongo
   volumes:
     - "/data/db:/data/db"
   ports:
     - "27017:27017"